name: Publish draft release

on:
  push:
    tags:
      # Catches v1.2.3 and v1.2.3-rc1
      - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  draft-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install Rust stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Export JSON with `tidefi-primitives-cli`
        run: |
          cargo run json -o ./dist

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/assets.json
            dist/networks.json
